import { shopProductPathSegment } from "@/lib/productSlug";
import type { StoreProduct } from "./types";

const IMG = "/murai/images/sarees";

/** Fallback catalog when MongoDB is unavailable — matches Murai reference UI. */
export const DEMO_SAREE_PRODUCTS: StoreProduct[] = [
  { _id: "demo-1", productId: "MURA-BAN-001", title: "Banarasi Silk Saree", category: "Silk Sarees", price: "3599", mrp: "5999", discountPercentage: 40, image: `${IMG}/banarasi.webp`, bannerImg: [`${IMG}/banarasi.webp`, `${IMG}/kanjivaram.webp`], stock: 12, ratings: 5, reviews: 48, description: "<p>Luxurious Banarasi silk saree with rich zari work. Perfect for weddings and festive occasions.</p>" },
  { _id: "demo-2", productId: "MURA-KAN-001", title: "Kanjivaram Silk Saree", category: "Kanjivaram", price: "4999", mrp: "7999", discountPercentage: 38, image: `${IMG}/kanjivaram.webp`, bannerImg: [`${IMG}/kanjivaram.webp`], stock: 8, ratings: 5, reviews: 36, description: "<p>Authentic Kanjivaram weave with temple border and vibrant silk body.</p>" },
  { _id: "demo-3", productId: "MURA-COT-001", title: "Cotton Block Print Saree", category: "Cotton Sarees", price: "899", mrp: "1499", discountPercentage: 40, image: `${IMG}/cotton-block.webp`, stock: 25, ratings: 4, reviews: 22, description: "<p>Lightweight cotton saree with hand block prints — ideal for daily wear.</p>" },
  { _id: "demo-4", productId: "MURA-GEO-001", title: "Georgette Party Saree", category: "Designer Sarees", price: "1299", mrp: "2199", discountPercentage: 41, image: `${IMG}/georgette-party.webp`, stock: 15, ratings: 5, reviews: 19, description: "<p>Elegant georgette saree with sequin work for parties and receptions.</p>" },
  { _id: "demo-5", productId: "MURA-CHI-001", title: "Chiffon Embroidered Saree", category: "Designer Sarees", price: "1599", mrp: "2499", discountPercentage: 36, image: `${IMG}/chiffon.webp`, stock: 11, ratings: 5, reviews: 16, description: "<p>Light chiffon saree with delicate embroidery for evening wear.</p>" },
  { _id: "demo-6", productId: "MURA-TUS-001", title: "Tussar Silk Saree", category: "Silk Sarees", price: "2199", mrp: "3499", discountPercentage: 37, image: `${IMG}/tussar.webp`, stock: 14, ratings: 5, reviews: 21, description: "<p>Natural tussar silk with earthy texture and subtle sheen.</p>" },
  { _id: "demo-7", productId: "MURA-PAT-001", title: "Patola Silk Saree", category: "Silk Sarees", price: "5499", mrp: "8999", discountPercentage: 39, image: `${IMG}/patola.webp`, stock: 5, ratings: 5, reviews: 12, description: "<p>Heritage Patola weave with double ikat patterns.</p>" },
  { _id: "demo-8", productId: "MURA-LIN-001", title: "Linen Cotton Saree", category: "Cotton Sarees", price: "1099", mrp: "1799", discountPercentage: 39, image: `${IMG}/linen-cotton.webp`, stock: 18, ratings: 4, reviews: 11, description: "<p>Breathable linen-cotton blend for summer comfort.</p>" },
  { _id: "demo-9", productId: "MURA-ORG-001", title: "Organza Designer Saree", category: "Designer Sarees", price: "1899", mrp: "2999", discountPercentage: 37, image: `${IMG}/organza.webp`, stock: 9, ratings: 5, reviews: 17, description: "<p>Sheer organza saree with contemporary designer embroidery.</p>" },
  { _id: "demo-10", productId: "MURA-MYS-001", title: "Mysore Silk Saree", category: "Silk Sarees", price: "3999", mrp: "5999", discountPercentage: 33, image: `${IMG}/mysore.webp`, stock: 7, ratings: 5, reviews: 28, description: "<p>Pure Mysore silk with classic gold border.</p>" },
  { _id: "demo-11", productId: "MURA-KAL-001", title: "Kalamkari Cotton Saree", category: "Cotton Sarees", price: "999", mrp: "1599", discountPercentage: 38, image: `${IMG}/kalamkari.webp`, stock: 20, ratings: 4, reviews: 15, description: "<p>Hand-painted Kalamkari motifs on soft cotton.</p>" },
  { _id: "demo-12", productId: "MURA-NET-001", title: "Net Party Wear Saree", category: "Designer Sarees", price: "1499", mrp: "2299", discountPercentage: 35, image: `${IMG}/net-party.webp`, stock: 13, ratings: 5, reviews: 18, description: "<p>Glamorous net saree with stone and sequin embellishments.</p>" },
  { _id: "demo-13", productId: "MURA-KAN-002", title: "Kanchipuram Silk Saree", category: "Kanjivaram", price: "5999", mrp: "8999", discountPercentage: 33, image: `${IMG}/kanchipuram.webp`, stock: 6, ratings: 5, reviews: 24, description: "<p>Traditional Kanchipuram silk with contrast pallu.</p>" },
].map((p) => ({ ...p, urlSlug: shopProductPathSegment(p) }));
